#!/usr/bin/ruby
# find all of the .avi's in the current directory

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: lsav [files]"

  opts.on("-D", "--[no-]dry", "Dry run (don't change anything") do |d|
    options[:dry] = true
  end
end.parse!

dirs = ARGV
if dirs.length == 0
  dirs = `ls -1 .`.split("\n")  
end

infile = ARGV
if infile.length == 0
  files = `ls -1`.split("\n")
  infile = files
end
movies = ['.avi', '.mov', '.mpeg', '.mpeg4']
infile.each do |f|
  ext = File.extname(f)
  next if not movies.include? ext.downcase
  puts f
end
